version: '2'
services:
  zookeeper:
    image: core/zookeeper
  kafka:
    image: core/kafka
    links:
      - zookeeper
    command: --peer zookeeper --bind=zookeeper:zookeeper.default
  helper:
    container_name: kafka_helper
    build:
      context: .
    links:
      - zookeeper
      - kafka
    command: /bin/sh
    stdin_open: true
    tty: true
